version: "25.0.2"
services:
  client:
    build: /
    container_name: prodify-client
    ports:
      - '3000:3000'
    # wont work in windows
    # volumes:
    #   - ./client/react:/prodify-client
    stdin_open: true
    tty: true
#     networks:
#       - docker-network
# networks:
#   docker-network:
#     external: true